parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'mysqli'
        url: '%env(resolve:DATABASE_URL)%'
        charset:  'UTF8'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
