parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
            connections:
                default:
                    driver: 'mysqli'
                    url: '%env(resolve:DATABASE_URL)%'
                    charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
