imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   "%test_database_name%"
        port:     "%test_database_port%"
        user:     "%test_database_user%"
        password: "%test_database_password%"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

assetic:
    filters:
        less:
            node: "%test_nodejs_executable%"
            node_paths: %test_nodejs_paths%

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
